#!/bin/bash

( cd ~/web/sunday9 ; git pull && hugo )
( cd ~/web/duncanbennie; git pull && hugo )

case "$OSTYPE" in
	linux*)
		rsync -rv ~/web/duncanbennie/public/* ~/.docker/swag/www/duncanbennie/
		rsync -rv ~/web/sunday9/public/* ~/.docker/swag/www/sunday9/
		;;
esac
