#!/bin/bash
##########################
# Copy to /usr/local/bin #
##########################
# Rsyncs Hugo directory  #
# to server.             #
##########################

rsync -rvu --exclude=".*" ~/duncanbennie/public/* sunday@vps.sunday9.xyz:~/.docker/swag/www/duncanbennie
